# CUDA_VISIBLE_DEVICES=0 python evaluate_model.py -m stain_modality.description=Merged_HE,Merged_KI67,Merged_GFAP,Merged_HE_KI67,Merged_HE_GFAP,Merged_HE_KI67_GFAP

hydra:
  searchpath:
    - /local/data1/chrsp39/Pancreas_Cancer_Deep_Learning_DPD_Images_Analysis/configs

# random seed for reproducibility
seed: 1
# classification task
task: 4_class
# number of classes 
n_classes: 4
# class labels
label_dict :
  0: 0
  1: 1
  2: 2
  3: 3
# path to csv file
csv_path: /local/data3/chrsp39/DPD-AI
# stratify samples by patient
patient_strat: False
# shuffle the data before training
shuffle: False
# information during the training
print_info: True
# results directory
results_dir: /local/data1/chrsp39/Pancreas_Cancer_Deep_Learning_DPD_Images_Analysis/models/CLAM/results
# whether model uses dropout
drop_out: False
# type of feature
feature_type: # options: conch_v1, conch_v1_5
# dimensionality of features
embed_dim:  # conch_v1 512, conchv1_5 768
# directory to features
data_root_dir: /local/data3/chrsp39/DPD-AI/${feature_type}
# experiment code to save eval results
save_exp_code: ${task}_${model_size}_${model_type}_${feature_type}
# experiment code to load trained models
models_exp_code: ${task}_${model_size}_${model_type}_${feature_type}_s1
# splits directory
splits_dir: /local/data1/chrsp39/Pancreas_Cancer_Deep_Learning_DPD_Images_Analysis/models/CLAM/
# size of model, does not affect mil, abmil
model_size: small # options: small, big (only for clam_sb, clam_mb)
# aggregation menthod
model_type: clam_sb # options: clam_sb, clam_mb, mil, abmil
# number of folds
k: 50
# start fold 
k_start: -1 # (default: -1, last fold)
# end fold
k_end: -1 # (default: -1, first fold)
# single fold to evaluate
fold: -1 # (default: -1)
# use micro_average instead of macro_avearge for multiclass AUC
micro_average: False
split: test # options: train, val, test, all
save_logits: False
ignore: null